{{- if include "alert-agent.hasSecrets" . }}
apiVersion: v1
kind: Secret
metadata:
  name: alert-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alert-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
