apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: alert-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alert-agent.labels" . | nindent 4 }}
